"""add_theme_etf_signals

Revision ID: 7d60a48c6196
Revises: b3c4d5e6f7a8
Create Date: 2026-06-12 01:54:53.640238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d60a48c6196'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme_etf_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('etf_symbol', sa.String(length=10), nullable=False),
    sa.Column('signal_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('avg_30d_volume', sa.Integer(), nullable=True),
    sa.Column('vol_ratio', sa.Float(), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('put_call_ratio', sa.Float(), nullable=True),
    sa.Column('otm_call_oi', sa.Integer(), nullable=True),
    sa.Column('total_call_oi', sa.Integer(), nullable=True),
    sa.Column('iv_percentile', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_etf_signals_etf_symbol'), 'theme_etf_signals', ['etf_symbol'], unique=False)
    op.create_index(op.f('ix_theme_etf_signals_signal_date'), 'theme_etf_signals', ['signal_date'], unique=False)
    op.create_index(op.f('ix_theme_etf_signals_theme_id'), 'theme_etf_signals', ['theme_id'], unique=False)
    op.drop_constraint(op.f('options_signals_symbol_signal_date_key'), 'options_signals', type_='unique')
    op.alter_column('theme_scores', 'unique_companies_selling',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('theme_scores', 'contracts_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('theme_scores', 'contracts_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('theme_scores', 'unique_companies_selling',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(op.f('options_signals_symbol_signal_date_key'), 'options_signals', ['symbol', 'signal_date'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_theme_etf_signals_theme_id'), table_name='theme_etf_signals')
    op.drop_index(op.f('ix_theme_etf_signals_signal_date'), table_name='theme_etf_signals')
    op.drop_index(op.f('ix_theme_etf_signals_etf_symbol'), table_name='theme_etf_signals')
    op.drop_table('theme_etf_signals')
    # ### end Alembic commands ###
